version: '3.4'

services: 
    react-chat-frontend:
        image: react-chat-frontend
        ports:
            - 80:9000
        volumes: 
            - .:/usr/src/app
    react-chat-backend:
        image: react-chat-backend
        ports: 
            - 5050:5050
        volumes: 
            - .:/usr/src/app
    mongo:
        image: mongo
        volumes: 
            - data:/data/db
    
volumes: 
    data:
